### ISSUE TITLE
2.7 converter 

### ISSUE THREAD

**Issue by ALeczkowski** [surfacesyntacticud/tools#12]
Hello,
I used the UD_to_SUD converter of the version tagged as 2.7 (on UD v2.7 data). However, I get different treebanks than SUD treebanks downloaded from here: https://surfacesyntacticud.github.io/data/.

I checked 3 treebanks (train sets only) that is I calculated UAS and LAS scores between a treebank set taken from the SUD website (v2.7) and a corresponding treebank set converted from UD version v2.7:
Polish LFG: UAS 100.00%   LAS 92.41%
Polish PDB: UAS 99.99%  LAS 86.39%
English GUM: UAS 100.00% LAS 94.09%

So I understand that the version of the converter tagged v2.7 is not the one with which SUD treebanks v2.7 where created. Or maybe I am doing something incorrectly? I would appreciate your comment or pointing me to the correct version of the converter.

**Comment by bguil** [comment]
Since version 1.4, Grew uses a new option on command line to deal with edge encoding (more detail below).
So the right command to convert UD to SUD with Grew ≥ 1.4 is:

```
grew transform -grs grs/UD_to_SUD.grs -config sud -i input_UD_file.conllu -o output_SUD_file.conllu
```

I'm very sorry for this. I should have updated the [README](https://github.com/surfacesyntacticud/tools/blob/master/converter/README.md) with this when Grew 1.4 as released (I've just done it now).

I've run the conversion again with the new command and I get set same output than the data from the tgz link on https://surfacesyntacticud.github.io/data/. 

---

Without the `config` option, the edge label is badly printed `deep=pass,1=subj`:
```
# sent_id = GUM_academic_exposure-17
…
4	results	result	NOUN	NNS	Number=Plur	9	deep=pass,1=subj	_	_
```

and with the `config` option, we get the right form `subj@pass`.

```
# sent_id = GUM_academic_exposure-17
…
4	results	result	NOUN	NNS	Number=Plur	9	subj@pass	_	_
```

**Comment by ALeczkowski** [comment]
Thanks!
